### PR TITLE
Replace slots with roles in the sample happ.yaml file

### PR DESCRIPTION
**Pull request by wimpheling**
It seems the yaml is outdated

### CODE REVIEW

**Comment by Connoropolous** [comment]
Nice. Is that all that's changed? (It works otherwise?)

**Comment by wimpheling** [comment]
Well as you can see in the pipeline "Cachix" doesn't work anymore. As I don't know what it is for, I just skipped that part when installing locally and the other steps were working.

**Comment by Connoropolous** [comment]
Since you didn't break the cachix thing, and you say it works locally apart from that, I will put an approve on it (it's fairly informal over here, but maybe we will wait for another approve from say... @guillemcordoba  since they're more in the loop than me?)

**Review by Connoropolous — APPROVED** [review]

**Comment by zippy** [comment]
I fixed this and also the CI in the latest update to 119.  Thanks!

**Pull request closed without merging**
